<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="JsonSchema.Net" Version="9.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cai.Reference.Scoring\Cai.Reference.Scoring.csproj" />
    <ProjectReference Include="..\..\src\Cai.Reference\Cai.Reference.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Vectors\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>